In [1]:

import numpy as np
import random as rm
import time
import pandas as pd
from numpy import linalg as LA

import random as rm
import time

In [2]:
#loading dataset
meteo_data=pd.read_csv("Meteorological_data.csv")
meteo_rain_data=meteo_data.filter(['Station_Name','Year','Month','Day','Rainfall in mm'])
meteo_rain_data

Station_Name  Year  Month  Day  Rainfall in mm
0       KADUHA_AWS  2018      1    1             0.2
1       KADUHA_AWS  2018      1    2             5.8
2       KADUHA_AWS  2018      1    3             2.6
3       KADUHA_AWS  2018      1    4             1.2
4       KADUHA_AWS  2018      1    5             1.4
..             ...   ...    ...  ...             ...
952  MUKUNGURI_AWS  2018     12   27             0.0
953  MUKUNGURI_AWS  2018     12   28             0.0
954  MUKUNGURI_AWS  2018     12   29             0.0
955  MUKUNGURI_AWS  2018     12   30             0.0
956  MUKUNGURI_AWS  2018     12   31             0.0

[957 rows x 5 columns]

In [3]:
#filtering the important columns to be used 
new_value=[]
for value in meteo_rain_data['Rainfall in mm']:
    if value!=0:
        value=1
    new_value.append(value)

meteo_rain_data['rain patterns']=new_value

meteo_rain_data
          
 

Station_Name  Year  Month  Day  Rainfall in mm  rain patterns
0       KADUHA_AWS  2018      1    1             0.2            1.0
1       KADUHA_AWS  2018      1    2             5.8            1.0
2       KADUHA_AWS  2018      1    3             2.6            1.0
3       KADUHA_AWS  2018      1    4             1.2            1.0
4       KADUHA_AWS  2018      1    5             1.4            1.0
..             ...   ...    ...  ...             ...            ...
952  MUKUNGURI_AWS  2018     12   27             0.0            0.0
953  MUKUNGURI_AWS  2018     12   28             0.0            0.0
954  MUKUNGURI_AWS  2018     12   29             0.0            0.0
955  MUKUNGURI_AWS  2018     12   30             0.0            0.0
956  MUKUNGURI_AWS  2018     12   31             0.0            0.0

[957 rows x 6 columns]

In [4]:
#getting the data of kaduha location from the dataset
kaduha_data=meteo_rain_data.loc[meteo_rain_data['Station_Name']=='KADUHA_AWS']
kaduha_data

Station_Name  Year  Month  Day  Rainfall in mm  rain patterns
0     KADUHA_AWS  2018      1    1             0.2            1.0
1     KADUHA_AWS  2018      1    2             5.8            1.0
2     KADUHA_AWS  2018      1    3             2.6            1.0
3     KADUHA_AWS  2018      1    4             1.2            1.0
4     KADUHA_AWS  2018      1    5             1.4            1.0
..           ...   ...    ...  ...             ...            ...
314   KADUHA_AWS  2018     12   27             3.8            1.0
315   KADUHA_AWS  2018     12   28             0.2            1.0
316   KADUHA_AWS  2018     12   29             4.2            1.0
317   KADUHA_AWS  2018     12   30             0.2            1.0
318   KADUHA_AWS  2018     12   31            11.2            1.0

[319 rows x 6 columns]

In [5]:
#Getting the data of Rutsiro location from the dataset
rutsiro_data=meteo_rain_data.loc[meteo_rain_data['Station_Name']=='RUTSIRO_AWS']
rutsiro_data

Station_Name  Year  Month  Day  Rainfall in mm  rain patterns
319  RUTSIRO_AWS  2018      1    1             0.8            1.0
320  RUTSIRO_AWS  2018      1    2             1.0            1.0
321  RUTSIRO_AWS  2018      1    3             0.6            1.0
322  RUTSIRO_AWS  2018      1    4             1.4            1.0
323  RUTSIRO_AWS  2018      1    5             2.2            1.0
..           ...   ...    ...  ...             ...            ...
633  RUTSIRO_AWS  2018     12   27             0.4            1.0
634  RUTSIRO_AWS  2018     12   28             0.0            0.0
635  RUTSIRO_AWS  2018     12   29             3.6            1.0
636  RUTSIRO_AWS  2018     12   30             3.6            1.0
637  RUTSIRO_AWS  2018     12   31             5.6            1.0

[319 rows x 6 columns]

In [6]:
#getting the data for mukunguri location from the dataset
mukunguri_data=meteo_rain_data.loc[meteo_rain_data['Station_Name']=='MUKUNGURI_AWS']
mukunguri_data

Station_Name  Year  Month  Day  Rainfall in mm  rain patterns
638  MUKUNGURI_AWS  2018      1    1             2.0            1.0
639  MUKUNGURI_AWS  2018      1    2             0.0            0.0
640  MUKUNGURI_AWS  2018      1    3             0.0            0.0
641  MUKUNGURI_AWS  2018      1    4            16.2            1.0
642  MUKUNGURI_AWS  2018      1    5             0.0            0.0
..             ...   ...    ...  ...             ...            ...
952  MUKUNGURI_AWS  2018     12   27             0.0            0.0
953  MUKUNGURI_AWS  2018     12   28             0.0            0.0
954  MUKUNGURI_AWS  2018     12   29             0.0            0.0
955  MUKUNGURI_AWS  2018     12   30             0.0            0.0
956  MUKUNGURI_AWS  2018     12   31             0.0            0.0

[319 rows x 6 columns]

In [7]:
# calculating the probability of getting rain followed by rain for kaduha location  in summer
kaduha_summer_data=kaduha_data.loc[(kaduha_data['Month']==6) | (kaduha_data['Month']==7) | (kaduha_data['Month']==8)]
kaduha_summer_total_days=kaduha_summer_data['rain patterns'].count()
weather_column=kaduha_summer_data['rain patterns']
rain_days=0
previous_day=1
for current_day in weather_column:
    if current_day==1 and previous_day==1:
        rain_days+=1
        previous_day=current_day
        
        
kaduha_rain_followed_by_rain_prob_summer=rain_days/kaduha_summer_total_days
print(f' The prob of rain followed by rain kaduha summer: {kaduha_rain_followed_by_rain_prob_summer}')

 The prob of rain followed by rain kaduha summer: 0.1724137931034483


In [8]:
# calculating the probability of getting rain followed by sun for kaduha location in summer     
rain_followed_by_sun_prob_summer=1-kaduha_rain_followed_by_rain_prob_summer
print(f' The prob of rain followed by sun kaduha summer :{rain_followed_by_sun_prob_summer}')

 The prob of rain followed by sun kaduha summer :0.8275862068965517


In [9]:
#calculating the probability of getting sun followed by rain for kaduha location  in summer
weather_column=kaduha_summer_data['rain patterns']
sun_rain_days=0
previous_day=0
for current_day in weather_column:
    if current_day==1 and previous_day==0:
        sun_rain_days+=1
        previous_day=current_day
        
        
kaduha_sun_followed_by_rain_prob_summer=sun_rain_days/kaduha_summer_total_days
kaduha_sun_followed_by_rain_prob_summer
print(f' The prob of sun followed by rain kaduha summer: {kaduha_sun_followed_by_rain_prob_summer}')

 The prob of sun followed by rain kaduha summer: 0.011494252873563218


In [10]:
# calculating the probability of getting sun followed by sun for kaduha location  in summer   
kaduha_sun_followed_by_sun_prob_summer=1-kaduha_sun_followed_by_rain_prob_summer
print(f' The prob of sun followed by sun kaduha summer: {kaduha_sun_followed_by_sun_prob_summer}')

 The prob of sun followed by sun kaduha summer: 0.9885057471264368


In [11]:
#kaduha summer state probabilities matrix
kaduha_summer_matrix = np.matrix([[kaduha_rain_followed_by_rain_prob_summer, rain_followed_by_sun_prob_summer],
                                  [kaduha_sun_followed_by_rain_prob_summer,kaduha_sun_followed_by_sun_prob_summer ]])

print(f' Kaduha summer matrix :\n\n{kaduha_summer_matrix}')

 Kaduha summer matrix :

[[0.17241379 0.82758621]
 [0.01149425 0.98850575]]


In [12]:
#kaduha summer steady states probabilities 
kaduha_summer_steady_list=[1,2, 11, 12]

for kaduha_summer_value in kaduha_summer_steady_list:
    print(f"\nKaduha summer steady state matrix power {kaduha_summer_value} is \n\n {LA.matrix_power(kaduha_summer_matrix,kaduha_summer_value)}\n")
    


Kaduha summer steady state matrix power 1 is 

 [[0.17241379 0.82758621]
 [0.01149425 0.98850575]]


Kaduha summer steady state matrix power 2 is 

 [[0.039239  0.960761 ]
 [0.0133439 0.9866561]]


Kaduha summer steady state matrix power 11 is 

 [[0.01369863 0.98630137]
 [0.01369863 0.98630137]]


Kaduha summer steady state matrix power 12 is 

 [[0.01369863 0.98630137]
 [0.01369863 0.98630137]]



In [13]:
# calculating the probability of getting sun followed by sun for kaduha location  in winter

kaduha_winter_data=kaduha_data.loc[(kaduha_data['Month']==3) | (kaduha_data['Month']==4) | (kaduha_data['Month']==5)]
kaduha_winter_total_days=kaduha_winter_data['Rainfall in mm'].count()


#days of getting sunny day given sunny day on previous day in winter kaduha

winter_weather_column=kaduha_winter_data['rain patterns']
sunny_days=0
previous_day=0
for current_day in winter_weather_column:
    if current_day==0 and previous_day==0:
        previous_day=current_day
        sunny_days+=1
        
        
kaduha_sun_followed_by_sun_prob_winter=sunny_days/kaduha_winter_total_days
print(f' The prob of sun followed by sun in winter kaduha winter: {kaduha_sun_followed_by_sun_prob_winter}')

 The prob of sun followed by sun in winter kaduha winter: 0.3815789473684211


In [15]:
#calculating the probability of getting rain followed by sun for kaduha location  in winter
winter_weather_column=kaduha_winter_data['rain patterns']
rain_sun_days=0
previous_day=1
for current_day in winter_weather_column:
    if current_day==0 and previous_day==1:
        rain_sun_days+=1
        previous_day=current_day
        
        
kaduha_rain_followed_by_sun_prob_winter=rain_sun_days/kaduha_winter_total_days
print(f' The prob of rain followed by sun kaduha winter: {kaduha_rain_followed_by_sun_prob_winter}')

 The prob of rain followed by sun kaduha winter: 0.013157894736842105


In [16]:
# calculating the probability of getting rain followed by rain for kaduha location in winter      
kaduha_rain_followed_by_rain_prob_winter=1-kaduha_rain_followed_by_sun_prob_winter
print(f' The prob of rain followed by rain kaduha winter: {kaduha_rain_followed_by_rain_prob_winter}')

 The prob of rain followed by rain kaduha winter: 0.9868421052631579


In [17]:
# calculating the probability of getting sun followed by rain for kaduha location  in winter    
        
kaduha_sun_followed_by_rain_prob_winter=1-kaduha_sun_followed_by_sun_prob_winter
print(f' The prob of sun followed by rain kaduha winter: {kaduha_sun_followed_by_rain_prob_winter}')

 The prob of sun followed by rain kaduha winter: 0.618421052631579


In [18]:

#kaduha winter state probabilities matrix for kaduha location in winter
kaduha_winter_state_probability_matrix = np.matrix([[kaduha_rain_followed_by_rain_prob_winter, kaduha_rain_followed_by_sun_prob_winter],
                                  [kaduha_sun_followed_by_rain_prob_winter,kaduha_sun_followed_by_sun_prob_winter ]])

print(f' Kaduha winter state probabilities  matrix :\n\n{kaduha_summer_matrix}')


 Kaduha winter state probabilities  matrix :

[[0.17241379 0.82758621]
 [0.01149425 0.98850575]]


In [19]:

#kaduha winter steady probabilities  in winter
kaduha_winter_steady_list=[1,2,21,22]

for kaduha_winter_value in kaduha_winter_steady_list:
    print(f"Kaduha winter  steady state matrix power {kaduha_winter_value} is: \n\n {LA.matrix_power(kaduha_winter_state_probability_matrix,kaduha_winter_value)}\n")


Kaduha winter  steady state matrix power 1 is: 

 [[0.98684211 0.01315789]
 [0.61842105 0.38157895]]

Kaduha winter  steady state matrix power 2 is: 

 [[0.98199446 0.01800554]
 [0.84626039 0.15373961]]

Kaduha winter  steady state matrix power 21 is: 

 [[0.97916667 0.02083333]
 [0.97916667 0.02083333]]

Kaduha winter  steady state matrix power 22 is: 

 [[0.97916667 0.02083333]
 [0.97916667 0.02083333]]



In [20]:
# calculating the probability of getting rain followed by rain for rutsiro location in summer

rutsiro_summer_data=rutsiro_data.loc[(rutsiro_data['Month']==6) | (rutsiro_data['Month']==7) | (rutsiro_data['Month']==8)]
rutsiro_summer_total_days=rutsiro_summer_data['rain patterns'].count()

rutsiro_summer_weather_column=rutsiro_summer_data['rain patterns']
rain_rain_days=0
previous_day=1
for current_day in rutsiro_summer_weather_column:
    if current_day==1 and previous_day==1:
        rain_rain_days+=1
        previous_day=current_day
        
        
rutsiro_rain_followed_by_rain_prob_summer=rain_rain_days/rutsiro_summer_total_days
print(f' The prob of rain followed by rain rutsiro summer: {rutsiro_rain_followed_by_rain_prob_summer}')

 The prob of rain followed by rain rutsiro summer: 0.21839080459770116


In [21]:
                
rutsiro_rain_followed_by_sun_prob_summer=1-rutsiro_rain_followed_by_rain_prob_summer
print(f' The prob of rain followed by sun rutsiro summer: {rutsiro_rain_followed_by_sun_prob_summer}')

 The prob of rain followed by sun rutsiro summer: 0.7816091954022988


In [22]:
# calculating the probability of getting sun followed by rain for rutsiro location in summer

rutsiro_summer_data=rutsiro_data.loc[(rutsiro_data['Month']==6) | (rutsiro_data['Month']==7) | (rutsiro_data['Month']==8)]
rutsiro_summer_total_days=rutsiro_summer_data['rain patterns'].count()

rutsiro_summer_weather_column=rutsiro_summer_data['rain patterns']
sun_rain_days=0
previous_day=0
for current_day in rutsiro_summer_weather_column:
    if current_day==1 and previous_day==0:
        sun_rain_days+=1
        previous_day=current_day
        
        
rutsiro_sun_followed_by_rain_prob_summer=sun_rain_days/rutsiro_summer_total_days
print(f' The prob of sun followed by rain rutsiro summer: {rutsiro_sun_followed_by_rain_prob_summer}')

 The prob of sun followed by rain rutsiro summer: 0.011494252873563218


In [23]:
# calculating the probability of getting sun followed by sun for for rutsiro location in summer
rutsiro_sun_followed_by_sun_prob_summer=1-rutsiro_sun_followed_by_rain_prob_summer
print(f' The prob of sun followed by sun rutsiro summer: {rutsiro_sun_followed_by_sun_prob_summer}')

 The prob of sun followed by sun rutsiro summer: 0.9885057471264368


In [24]:

#rutsiro state probabilities matrix for rutsiro location in summer
rutsiro_summer_state_probability_matrix = np.matrix([[rutsiro_rain_followed_by_rain_prob_summer, rutsiro_rain_followed_by_sun_prob_summer],
                                  [rutsiro_sun_followed_by_rain_prob_summer,rutsiro_sun_followed_by_sun_prob_summer]])

print(f' Rutsiro summer matrix :\n\n{rutsiro_summer_state_probability_matrix}')

 Rutsiro summer matrix :

[[0.2183908  0.7816092 ]
 [0.01149425 0.98850575]]


In [25]:
#rutsiro summer steady states probabilities 
rutsiro_summer_steady_list=[1,2,13,15,16]

for rutsiro_summer_value in rutsiro_summer_steady_list:
    print(f"Rutsiro summer steady states prob matrix power {rutsiro_summer_value} is: \n\n {LA.matrix_power(rutsiro_summer_state_probability_matrix,rutsiro_summer_value)}\n")


Rutsiro summer steady states prob matrix power 1 is: 

 [[0.2183908  0.7816092 ]
 [0.01149425 0.98850575]]

Rutsiro summer steady states prob matrix power 2 is: 

 [[0.05667856 0.94332144]
 [0.01387237 0.98612763]]

Rutsiro summer steady states prob matrix power 13 is: 

 [[0.01449275 0.98550725]
 [0.01449275 0.98550725]]

Rutsiro summer steady states prob matrix power 15 is: 

 [[0.01449275 0.98550725]
 [0.01449275 0.98550725]]

Rutsiro summer steady states prob matrix power 16 is: 

 [[0.01449275 0.98550725]
 [0.01449275 0.98550725]]



In [26]:
# calculating the probability of getting sun followed by sun for rutsiro location in winter

rutsiro_winter_data=rutsiro_data.loc[(rutsiro_data['Month']==3) | (rutsiro_data['Month']==4) | (rutsiro_data['Month']==5)]

rutsiro_winter_total_days=rutsiro_winter_data['Rainfall in mm'].count()


rutsiro_winter_weather_column=rutsiro_winter_data['rain patterns']
sun_sun_days=0
previous_day=0
for current_day in rutsiro_winter_weather_column:
    if current_day==0 and previous_day==0:
        sun_sun_days+=1
        previous_day=current_day
        
        
rutsiro_sun_followed_by_sun_prob_winter=sun_sun_days/rutsiro_winter_total_days
print(f' The prob of sun followed by sun rutsiro winter: {rutsiro_sun_followed_by_sun_prob_winter}')

 The prob of sun followed by sun rutsiro winter: 0.4342105263157895


In [27]:
# calculating the probability of getting sun followed by rain for rutsiro location in winter

rutsiro_winter_data=rutsiro_data.loc[(rutsiro_data['Month']==3) | (rutsiro_data['Month']==4) | (rutsiro_data['Month']==5)]
        
rutsiro_sun_followed_by_rain_prob_winter=1-rutsiro_sun_followed_by_sun_prob_winter
print(f' The prob of sun followed by rain rutsiro winter: {rutsiro_sun_followed_by_rain_prob_winter}')

 The prob of sun followed by rain rutsiro winter: 0.5657894736842105


In [28]:
# calculating the probability of getting rain followed by sun for rutsiro location in winter

rutsiro_winter_data=rutsiro_data.loc[(rutsiro_data['Month']==3) | (rutsiro_data['Month']==4) | (rutsiro_data['Month']==5)]

rutsiro_winter_total_days=rutsiro_winter_data['Rainfall in mm'].count()


rutsiro_winter_weather_column=rutsiro_winter_data['rain patterns']
rain_sun_days=0
previous_day=1
for current_day in rutsiro_winter_weather_column:
    if current_day==0 and previous_day==1:
        rain_sun_days+=1
        previous_day=current_day
        
        
rutsiro_rain_followed_by_sun_prob_winter=rain_sun_days/rutsiro_winter_total_days
print(f' The prob of rain followed by sun rutsiro winter: {rutsiro_rain_followed_by_sun_prob_winter}')

 The prob of rain followed by sun rutsiro winter: 0.013157894736842105


In [29]:
# calculating the probability of getting rain followed by rain for rutsiro location  in winter

rutsiro_rain_followed_by_rain_prob_winter=1-rutsiro_rain_followed_by_sun_prob_winter
print(f' The prob of rain followed by rain rutsiro winter: {rutsiro_rain_followed_by_rain_prob_winter}')

 The prob of rain followed by rain rutsiro winter: 0.9868421052631579


In [30]:

#rutsiro winter steady states probabilities matrix 

rutsiro_winter_state_probability_matrix = np.matrix([[rutsiro_rain_followed_by_rain_prob_winter, rutsiro_rain_followed_by_sun_prob_winter],
                                  [rutsiro_sun_followed_by_rain_prob_winter,rutsiro_sun_followed_by_sun_prob_winter]])

print(f' Rutsiro winter matrix :\n\n{rutsiro_winter_state_probability_matrix}')

 Rutsiro winter matrix :

[[0.98684211 0.01315789]
 [0.56578947 0.43421053]]


In [31]:
#rutsiro winter steady states probabilities  
rutsiro_winter_steady_list=[1,2,22,23,24]

for rutsiro_winter_value in rutsiro_winter_steady_list:
    print(f"Rutsiro winter steady states prob matrix power {rutsiro_winter_value} is: \n\n {LA.matrix_power(rutsiro_winter_state_probability_matrix,rutsiro_winter_value)}\n")


Rutsiro winter steady states prob matrix power 1 is: 

 [[0.98684211 0.01315789]
 [0.56578947 0.43421053]]

Rutsiro winter steady states prob matrix power 2 is: 

 [[0.98130194 0.01869806]
 [0.80401662 0.19598338]]

Rutsiro winter steady states prob matrix power 22 is: 

 [[0.97727273 0.02272727]
 [0.97727272 0.02272728]]

Rutsiro winter steady states prob matrix power 23 is: 

 [[0.97727273 0.02272727]
 [0.97727273 0.02272727]]

Rutsiro winter steady states prob matrix power 24 is: 

 [[0.97727273 0.02272727]
 [0.97727273 0.02272727]]



In [32]:
# calculating the probability of getting rain followed by rain for mukunguri location  in summer

mukunguri_summer_data=mukunguri_data.loc[(mukunguri_data['Month']==6) | (mukunguri_data['Month']==7) | (mukunguri_data['Month']==8)]
mukunguri_summer_data

mukunguri_summer_total_days=mukunguri_summer_data['rain patterns'].count()


mukunguri_summer_weather_column=mukunguri_summer_data['rain patterns']
rain_rain_days=0
previous_day=1
for current_day in mukunguri_summer_weather_column:
    if current_day==1 and previous_day==1:
        rain_rain_days+=1
        previous_day=current_day
        
        
mukunguri_rain_followed_by_rain_prob_summer=rain_rain_days/mukunguri_summer_total_days
print(f' The prob of rain followed by rain mukunguri summer: {mukunguri_rain_followed_by_rain_prob_summer}')

 The prob of rain followed by rain mukunguri summer: 0.011494252873563218


In [33]:
# calculating the probability of getting sun followed by rain for mukunguri location  in summer

mukunguri_summer_data=mukunguri_data.loc[(mukunguri_data['Month']==6) | (mukunguri_data['Month']==7) | (mukunguri_data['Month']==8)]
mukunguri_summer_data

mukunguri_summer_total_days=mukunguri_summer_data['rain patterns'].count()


mukunguri_summer_weather_column=mukunguri_summer_data['rain patterns']
sun_rain_days=0
previous_day=0
for current_day in mukunguri_summer_weather_column:
    if current_day==1 and previous_day==0:
        sun_rain_days+=1
        previous_day=current_day
        
        
mukunguri_sun_followed_by_rain_prob_summer=sun_rain_days/mukunguri_summer_total_days
print(f' The prob of sun followed by rain mukunguri summer: {mukunguri_sun_followed_by_rain_prob_summer}')

 The prob of sun followed by rain mukunguri summer: 0.011494252873563218


In [34]:
# calculating the probability of getting rain followed by sun for mukunguri location  in summer

mukunguri_summer_data=mukunguri_data.loc[(mukunguri_data['Month']==6) | (mukunguri_data['Month']==7) | (mukunguri_data['Month']==8)]
mukunguri_summer_data
        
        
mukunguri_rain_followed_by_sun_prob_summer=1-mukunguri_rain_followed_by_rain_prob_summer
print(f' The prob of rain followed by sun mukunguri summer: {mukunguri_rain_followed_by_sun_prob_summer}')

 The prob of rain followed by sun mukunguri summer: 0.9885057471264368


In [35]:
# calculating the probability of getting sun followed by sun for mukunguri location  in summer

mukunguri_sun_followed_by_sun_prob_summer=1-mukunguri_sun_followed_by_rain_prob_summer
print(f' The prob of sun followed by sun mukunguri summer: {mukunguri_sun_followed_by_sun_prob_summer}')

 The prob of sun followed by sun mukunguri summer: 0.9885057471264368


In [36]:
#Mukunguri summer steady states probabilities matrix 

mukunguri_summer_state_probability_matrix = np.matrix([[mukunguri_rain_followed_by_rain_prob_summer, mukunguri_rain_followed_by_sun_prob_summer],
                                  [mukunguri_sun_followed_by_rain_prob_summer,mukunguri_sun_followed_by_sun_prob_summer]])

print(f' Mukunguri summer matrix :\n\n{mukunguri_summer_state_probability_matrix}')

 Mukunguri summer matrix :

[[0.01149425 0.98850575]
 [0.01149425 0.98850575]]


In [37]:
#kaduha summer steady states probabilities 
mukunguri_summer_steady_list=[1,2,3]

for mukunguri_summer_value in mukunguri_summer_steady_list:
    print(f"Mukunguri Summer steady states prob matrix power {mukunguri_summer_value} is: \n\n {LA.matrix_power(mukunguri_summer_state_probability_matrix,mukunguri_summer_value)}\n")



Mukunguri Summer steady states prob matrix power 1 is: 

 [[0.01149425 0.98850575]
 [0.01149425 0.98850575]]

Mukunguri Summer steady states prob matrix power 2 is: 

 [[0.01149425 0.98850575]
 [0.01149425 0.98850575]]

Mukunguri Summer steady states prob matrix power 3 is: 

 [[0.01149425 0.98850575]
 [0.01149425 0.98850575]]



In [38]:
# calculating the probability of getting rain followed by rain for mukunguri location  in summer

mukunguri_winter_data=mukunguri_data.loc[(mukunguri_data['Month']==3) | (mukunguri_data['Month']==4) | (mukunguri_data['Month']==5)]
mukunguri_winter_data



Station_Name  Year  Month  Day  Rainfall in mm  rain patterns
676  MUKUNGURI_AWS  2018      3    2             7.0            1.0
677  MUKUNGURI_AWS  2018      3    3             1.8            1.0
678  MUKUNGURI_AWS  2018      3    4             3.4            1.0
679  MUKUNGURI_AWS  2018      3    5            15.4            1.0
680  MUKUNGURI_AWS  2018      3   12             0.4            1.0
..             ...   ...    ...  ...             ...            ...
747  MUKUNGURI_AWS  2018      5   26             0.0            0.0
748  MUKUNGURI_AWS  2018      5   27             0.0            0.0
749  MUKUNGURI_AWS  2018      5   28             0.0            0.0
750  MUKUNGURI_AWS  2018      5   29             0.0            0.0
751  MUKUNGURI_AWS  2018      5   30             0.0            0.0

[76 rows x 6 columns]

In [39]:
# calculating the probability of getting sun followed by sun for mukunguri location  in winter

mukunguri_winter_data=mukunguri_data.loc[(mukunguri_data['Month']==3) | (mukunguri_data['Month']==4) | (mukunguri_data['Month']==5)]
mukunguri_winter_data


mukunguri_winter_total_days=mukunguri_winter_data['rain patterns'].count()


mukunguri_winter_weather_column=mukunguri_winter_data['rain patterns']

sun_sun_days=0
previous_day=0
for current_day in mukunguri_winter_weather_column:
    if current_day==0 and previous_day==0:
        sun_sun_days+=1
        previous_day=current_day
        
        
mukunguri_sun_followed_by_sun_prob_winter=sun_sun_days/mukunguri_winter_total_days
print(f' The prob of sun followed by sun mukunguri winter: {mukunguri_sun_followed_by_sun_prob_winter}')

 The prob of sun followed by sun mukunguri winter: 0.5921052631578947


In [40]:
        
# calculating the probability of getting sun followed by rain for mukunguri location  in winter 

mukunguri_sun_followed_by_rain_prob_winter=1-mukunguri_sun_followed_by_sun_prob_winter
print(f' The prob of sun followed by rain mukunguri winter: {mukunguri_sun_followed_by_rain_prob_winter}')

 The prob of sun followed by rain mukunguri winter: 0.4078947368421053


In [41]:
# calculating the probability of getting rain followed by sun for mukunguri location  in winter

mukunguri_winter_data=mukunguri_data.loc[(mukunguri_data['Month']==3) | (mukunguri_data['Month']==4) | (mukunguri_data['Month']==5)]
mukunguri_winter_data


mukunguri_winter_total_days=mukunguri_winter_data['rain patterns'].count()


mukunguri_winter_weather_column=mukunguri_winter_data['rain patterns']

rain_sun_days=0
previous_day=1
for current_day in mukunguri_winter_weather_column:
    if current_day==0 and previous_day==1:
        rain_sun_days+=1
        previous_day=current_day
        
        
mukunguri_rain_followed_by_sun_prob_winter=rain_sun_days/mukunguri_winter_total_days
print(f' The prob of rain followed by sun mukunguri winter: {mukunguri_rain_followed_by_sun_prob_winter}')

 The prob of rain followed by sun mukunguri winter: 0.013157894736842105


In [42]:
# calculating the probability of getting rain followed by rain for mukunguri location  in winter

mukunguri_rain_followed_by_rain_prob_winter=1-mukunguri_rain_followed_by_sun_prob_winter
print(f' The prob of rain followed by rain mukunguri winter: {mukunguri_rain_followed_by_rain_prob_winter}')

 The prob of rain followed by rain mukunguri winter: 0.9868421052631579


In [43]:
#Mukunguri winter  steady state probabilities matrix

mukunguri_winter_state_probability_matrix = np.matrix([[mukunguri_rain_followed_by_rain_prob_winter, mukunguri_rain_followed_by_sun_prob_winter],
                                  [mukunguri_sun_followed_by_rain_prob_winter,mukunguri_sun_followed_by_sun_prob_winter]])

print(f' Mukunguri winter matrix :\n\n{mukunguri_winter_state_probability_matrix}')

 Mukunguri winter matrix :

[[0.98684211 0.01315789]
 [0.40789474 0.59210526]]


In [44]:
#mukunguri winter steady states probabilities 
mukunguri_winter_steady_list=[1,2,33,34]

for mukunguri_winter_value in mukunguri_winter_steady_list:
    print(f"Mukunguri winter steady states prob matrix power {mukunguri_winter_value} is: \n\n {LA.matrix_power(mukunguri_winter_state_probability_matrix,mukunguri_winter_value)}\n")


Mukunguri winter steady states prob matrix power 1 is: 

 [[0.98684211 0.01315789]
 [0.40789474 0.59210526]]

Mukunguri winter steady states prob matrix power 2 is: 

 [[0.97922438 0.02077562]
 [0.64404432 0.35595568]]

Mukunguri winter steady states prob matrix power 33 is: 

 [[0.96875    0.03125   ]
 [0.96874999 0.03125001]]

Mukunguri winter steady states prob matrix power 34 is: 

 [[0.96875    0.03125   ]
 [0.96874999 0.03125001]]



In [45]:


# Let's define the statespace
states = ["Winter","Summer"]

# Possible sequences of events
days_behaviour = [["Sunny","Rainy"],["Sunny","Rainy"]]





kaduha_probabilities=[[kaduha_sun_followed_by_rain_prob_summer,kaduha_sun_followed_by_sun_prob_summer],[kaduha_rain_followed_by_rain_prob_winter,kaduha_rain_followed_by_sun_prob_winter]]
rutsiro_probabilities=[[rutsiro_sun_followed_by_rain_prob_summer,rutsiro_sun_followed_by_sun_prob_summer],[rutsiro_rain_followed_by_rain_prob_winter,rutsiro_rain_followed_by_sun_prob_winter]]
mukunguri_probabilities=[[mukunguri_sun_followed_by_rain_prob_summer,mukunguri_sun_followed_by_sun_prob_summer],[mukunguri_rain_followed_by_rain_prob_winter,mukunguri_rain_followed_by_sun_prob_winter]]


# A functions which implements the Markov model to forecast the weather

def location_weather_prediction(days_forecast):
    # There is no reason to start from one state or another, let's just
    # pick one randomly
    weatherToday = rm.choice(states)
    day = 0
    print(f"Initial weather: {weatherToday}\n")
    print('    Kaduha')
    print('**************')
    while day < days_forecast:
        if weatherToday == "Winter":
            #numpy.random.choice(a, size=None, replace=True, p=None)
            change = np.random.choice(days_behaviour[0],replace=True,p=kaduha_probabilities[0])
            if change == "Rainy":
                pass
            else:
                change = "Sunny"
        elif weatherToday == "Summer":
            change = np.random.choice(days_behaviour[1],replace=True,p=kaduha_probabilities[1])
            if change == "Sunny":
                pass
            else:
                change = "Rainy"
        print(change)
        day += 1
        time.sleep(0.5)
        
    #Rutsiro
    day = 0
    print('\n   Rutsiro')
    print('*****************')
    while day < days_forecast:
        if weatherToday == "Winter":
            #numpy.random.choice(a, size=None, replace=True, p=None)
            change = np.random.choice(days_behaviour[0],replace=True,p=rutsiro_probabilities[0])
            if change == "Rainy":
                pass
            else:
                change = "Sunny"
        elif weatherToday == "Summer":
            change = np.random.choice(days_behaviour[1],replace=True,p=rutsiro_probabilities[1])
            if change == "Sunny":
                pass
            else:
                change = "Rainy"
        print(change)
        day += 1
        time.sleep(0.5)
        
    #Mukungura
    day = 0
    print('\n      Mukungura')
    print('*******************************')
    while day < days_forecast:
        if weatherToday == "Winter":
            #numpy.random.choice(a, size=None, replace=True, p=None)
            change = np.random.choice(days_behaviour[0],replace=True,p=mukunguri_probabilities[0])
            if change == "Rainy":
                pass
            else:
                change = "Sunny"
        elif weatherToday == "Summer":
            change = np.random.choice(days_behaviour[1],replace=True,p=mukunguri_probabilities[1])
            if change == "Sunny":
                pass
            else:
                change = "Rainy"
        print(change)
        day += 1
        time.sleep(0.5)
        
    

# We forecast the weather for n days
location_weather_prediction(5)

Initial weather: Summer

    Kaduha
**************
Sunny
Sunny
Sunny
Sunny
Sunny

   Rutsiro
*****************
Sunny
Sunny
Sunny
Rainy
Sunny

      Mukungura
*******************************
Sunny
Rainy
Sunny
Sunny
Sunny
